import Link from "next/link";
import { FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const sections = [
  { title: "Service scope", items: ["HumanOS AI provides AI-assisted chat, memory, productivity, document, career, study, research, and planner workflows.", "AI responses are generated by configured providers and may be inaccurate, incomplete, or outdated.", "Users are responsible for reviewing AI outputs before making legal, medical, financial, hiring, academic, or career decisions."] },
  { title: "Accounts and acceptable use", items: ["Users must keep login credentials secure and use the product lawfully.", "Users may not upload illegal content, malware, secrets they do not have permission to use, or content that violates third-party rights.", "Workspace owners are responsible for their users, subscription, compliance requirements, and production configuration."] },
  { title: "Subscriptions", items: ["Paid plan access, limits, checkout, billing portal, and webhook enforcement depend on the configured payment provider.", "The app includes subscription plumbing, but each production operator must configure their own payment account, products, prices, taxes, and invoices.", "Plan limits may be changed for commercial, operational, or abuse-prevention reasons."] },
  { title: "Ownership and liability", items: ["Users retain ownership of their uploaded content subject to the rights needed to operate the service.", "HumanOS AI is provided as-is unless a separate written agreement says otherwise.", "The operator is not liable for indirect, incidental, consequential, or business-loss damages to the maximum extent allowed by law."] },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background px-4 py-10 text-foreground sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl">
        <Button asChild variant="ghost" size="sm"><Link href="/">Back to HumanOS AI</Link></Button>
        <div className="mt-8">
          <p className="flex items-center gap-2 text-sm font-semibold text-primary"><FileText className="h-4 w-4" /> Legal</p>
          <h1 className="mt-3 text-4xl font-semibold sm:text-5xl">Terms of Service</h1>
          <p className="mt-4 text-base leading-7 text-muted-foreground">Commercial terms for using HumanOS AI as an AI life and career copilot.</p>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: July 5, 2026</p>
        </div>
        <div className="mt-8 space-y-4">
          {sections.map((section) => <Card key={section.title} className="bg-card/70 backdrop-blur-2xl"><CardHeader><CardTitle className="text-xl">{section.title}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm leading-7 text-muted-foreground">{section.items.map((item) => <p key={item}>- {item}</p>)}</CardContent></Card>)}
        </div>
        <p className="mt-8 rounded-lg border bg-card/70 p-4 text-sm leading-7 text-muted-foreground">This template is not legal advice. Review and adapt it before selling to real customers.</p>
      </div>
    </main>
  );
}
